
# to run on docker hub

# version: "3.9"

# services:
#   backend:
#     image: notjovian/techjam2025-backend:1.0.0
#     container_name: backend
#     ports:
#       - "8000:8000"
#     networks:
#       - techjam-net

#   frontend:
#     image: notjovian/techjam2025-frontend:1.0.0
#     container_name: frontend
#     ports:
#       - "5173:5173"
#     environment:
#       - VITE_API_URL=http://backend:8000  # frontend can call backend inside network
#     networks:
#       - techjam-net

# networks:
#   techjam-net:
#     driver: bridge




# to run locally

services:
  backend:
    build: ./Agents
    container_name: backend_service
    ports:
      - "5001:5000"   # host:container
    networks:
      - app-net

  frontend:
    build: ./FE
    container_name: frontend_service
    ports:
      - "3000:5173"   # host:container
    networks:
      - app-net
    environment:
      - VITE_API_URL=http://backend:5000   # frontend talks to backend via service name

networks:
  app-net:
