version: "3.9"

services:
  backend:
    image: notjovian/techjam2025-backend:1.0.0
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - techjam-net

  frontend:
    image: notjovian/techjam2025-frontend:1.0.0
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8000  # frontend can call backend inside network
    networks:
      - techjam-net

networks:
  techjam-net:
    driver: bridge
