version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "5000:5000"
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    networks:
      - app-net
    environment:
      - VITE_API_URL=http://backend:5000   # frontend talks to backend via service name

networks:
  app-net:
